name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"
